apiVersion: apps/v1
kind: Deployment
metadata:
  name: appuser-middleware
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appuser-middleware
  template:
    metadata:
      labels:
        app: appuser-middleware
    spec:
      containers:
      - name: appuser-middleware
        image: uhub.service.ucloud.cn/entropypool/appuser-middleware:latest
        imagePullPolicy: Never
        volumeMounts:
          - name: service-config
            mountPath: /app
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: ENV_CLUSTER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: appuser-middleware-config
            items:
              - key: service-conf
                path: AppUserManager.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: appuser-middleware
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 50320
    targetPort: 50320
  - name: grpc
    port: 50321
    targetPort: 50321
  - name: prometheus
    port: 50322
    targetPort: 50322
  selector:
    app: appuser-middleware
