apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-appuser-middleware-prefix
  namespace: kube-system
spec:
  stripPrefix:
    prefixes:
      - /api/appuser-middleware
